### ISSUE TITLE
[Task] Research NestJS

### ISSUE THREAD

**Issue by olololoe110399** [VTNPlusD/tech#12]
1. Plan: 
2. Actual:
3. Next:
4. Issue:
Deadline: 28/03/2021

**Comment by nhathuy2401** [comment]
1 : Plan : Set up typescript , reseach typescript 
2 : Actual : Typescipt Datatype , Variable, set up 
3 : Next : Operator ,  function , arrow 
4 : Issue : None

**Comment by nhathuy2401** [comment]
Plan : Function arrow typescipt
Actual : Problem on OS 
Next : Learn Function arrow tpc 
Issue : Fixing problem on OS

**Comment by nhathuy2401** [comment]
1/ What did you do yesterday?
I'm research Typescript;
2/What will you do today?
Learning Function Arrow , Return function , Arrays , Variable,Scope
3/Listing blocker or problem  you're facing?
None

**Comment by tranquocviet226** [comment]
Close cái này nhé, mai làm task khác được chưa em

**Comment by nhathuy2401** [comment]
1/ What did you do yesterday?
Learning Function Arrow , Return function , Arrays , Variable,Scope
2/What will you do today?
Access Modified,Override , inheritance 
3/Listing blocker or problem you're facing?
None

**Comment by nhathuy2401** [comment]
1/ What did you do yesterday?
Access Modified,Override , inheritance
2/What will you do today?
I will be offf
3/Listing blocker or problem you're facing?
None
