### ISSUE TITLE
[Task] Research typescript

### ISSUE THREAD

**Issue by olololoe110399** [VTNPlusD/tech#21]
Format Report:
1. Plan:
2. Actual:
3. Next:
4. Issue:
Deadline: 30/03/2021

**Comment by duclinh21122000** [comment]
Hello Mr. Duy,
Em là Linh
Tại vì hôm nay em bận chạy dự án bên công ty nên hôm qua ngày 28/03 em có nghiên cứu một chút về TypeScript như là:
- Khái niệm: TypeScript là một dự án mã nguồn mở được phát triển bởi Microsoft, nó có thể được coi là một phiên bản nâng cao của Javascript bởi việc bổ sung tùy chọn kiểu tĩnh và lớp hướng đối tượng mà điều này không có ở Javascript.
- Ưu điểm:
  + Dễ phát triển dự án lớn.
  + Nhiều Framework lựa chọn.
  + Hỗ trợ các tính năng của Javascript phiên bản mới nhất.
  + Là mã nguồn mở.
- Các loại cơ bản của TypeScript: boolean, number, string, array, enum, any, void.
- Cách khai báo:  var tên_biến : kiểu_trả_về = giá_trị_biến; Ví dụ: var name: String = "Linh";
- Về Function: Có 2 cách khai báo function tương tự với JavaScript:
 + Named function
              function add(x, y) {
                  return x+y;
              }
 + Anonymous function
              var myAdd = function(x, y) {
                                         return x+y; 
                                        };

**Comment by tranquocviet226** [comment]
Hôm nay em tiếp tục research typescript nhé, ngày mai cài đặt biến môi trường và build source
