### ISSUE TITLE
[Task] Cài đặt môi trường, build source code

### ISSUE THREAD

**Issue by tranquocviet226** [VTNPlusD/tech#24]
Format Report:
1. Plan:
2. Actual:
3. Next:
4. Issue:
Deadline: 30/03/2021

**Comment by duclinh21122000** [comment]
Em done task nha anh
![image](https://user-images.githubusercontent.com/61076909/112856134-ae35da80-90d9-11eb-928b-e0c5e43f2e3d.png)
